### ISSUE TITLE
Potentially unhandled rejection [3] Error: read ECONNRESET

### ISSUE THREAD

**Issue by resyst-it** [taigaio/taiga-events#10]
Hello,

I want to try taiga in my own server. But i have in error in my web browser : Something happened and our Oompa Loompas are working on it.

In my logs in /home/taiga/logs i have this error : 
Potentially unhandled rejection [3] Error: read ECONNRESET

Do you have an idea ?

Thank you.

**Comment by carloscaverobarca** [comment]
Hi,

See this answer, I had the same error and i fixed this way,

https://groups.google.com/forum/#!msg/taigaio/AKo5VCNrLAc/A5NziET5GAAJ

Regards.
Carlos.
