### ISSUE TITLE
Please edit the documentation to make it clear that taiga-events and taiga-back require the same secret key!

### ISSUE THREAD

**Issue by bwq** [taigaio/taiga-events#14]
From the documentation it's not clear that "SECRET_KEY" in  ~/taiga-back/settings/local.py and "secret" in ~/taiga-events/config.json should be identical. I assumed they required seperate secrets. 

This made it pretty hard to debug since the web socket connection works fine (shows up in console as connected), it just won't receive any messages.

**Comment by juanfran** [comment]
done https://github.com/taigaio/taiga-doc/commit/a3dc89f2f6f09d0363978a2452fb552ea6601245

thanks for the feedback!
