### ISSUE TITLE
Is 'secret'  the same thing as the 'erlang-cookie'?

### ISSUE THREAD

**Issue by douglasmiranda** [taigaio/taiga-events#17]
I don't  know if I'm missing something, but I didn't find in the documentation.

```json
{
    "url": "amqp://taiga:taiga@rabbitmq:5672/taiga",
    "secret": "secret"
}
```

https://www.rabbitmq.com/clustering.html#erlang-cookie

Or isn't related at all?

**Comment by juanfran** [comment]
no, it isn't related, that `secret` must be the same as SECRET_KEY in `~/taiga-back/settings/local.py`

**Comment by Hugodby** [comment]
I know the issue is closed but it will be nice to add that info into the documentation. It isn't clear by itself...
