### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 426

### ISSUE THREAD

**Issue by kstefanini** [taigaio/taiga-events#18]
Hello, I have this error who's a bit different from others found here by its code 426.
I've checked my config files according to previous issues replies, without success.

Part of local.py:

``` python
from .common import *

SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "taiga.tela-botanica.net"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:<<password>>@localhost:5672/taiga"}
```

config.json 

``` json
{
    "url": "amqp://taiga:<<password>>@localhost:5672/taiga",
    "secret": "<<secret>>",
    "webSocketServer": {
        "port": 8888
    }
}
```

If i try to ~/taiga-events$ coffee index.coffee 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
  at errnoException (net.js:904:11)
  at Server._listen2 (net.js:1042:14)
  at listen (net.js:1064:10)
  at net.js:1146:9
  at dns.js:72:18
  at process._tickCallback (node.js:419:13)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:906:3
```

And ~$ circusctl 

```
circusctl 0.14.0
circusd-stats: active
taiga: active
taiga-events: active
```

Any help appreciated :)

**Comment by juanfran** [comment]
Hi!

`Error: listen EADDRINUSE` usually means that the port number is already in use.

**Comment by kstefanini** [comment]
Hi, i've some news, the `Error: listen EADDRINUSE` was due to lake of `circusctl stop` before testing, so yeah, port was already in use, by node. 
After a `circusctl stop` i get an error free response from `~/taiga-events$ coffee index.coffee`.

And the `Unexpected response code: 426` was due to my apache proxy config. Taiga server is behind an Apache proxy, who missed some websocket proxying config. And [this](https://stackoverflow.com/questions/27526281/websockets-and-apache-proxy-how-to-configure-mod-proxy-wstunnel) gave me a solution.
