### ISSUE TITLE
Trying to run coffee throws error

### ISSUE THREAD

**Issue by shuron77** [taigaio/taiga-events#23]
Following the instructions for a production setup, finishing and attempting a test
Taiga-Events stops it forcefully every time a request is made to the webpage.
In troubleshooting I tried manually running
`coffee index.coffee`
To which it gives me this error
[PasteBin Link](http://pastebin.com/Kf8tdMw6)

**Comment by bameda** [comment]
Hi @shuron77 you are using an old version of node, please upgrade node to a version >= 6.0 (The current stable is 7.5.0 and the last LTS is 6.9.5 LTS).
