### ISSUE TITLE
Taiga events: coffee returned error not typed array

### ISSUE THREAD

**Issue by fabianfritz** [taigaio/taiga-events#25]
Hey,

I have an issue while setup taiga events on my brand new linux system.

I use this description 
https://taigaio.github.io/taiga-doc/dist/setup-production.html#_frontend_installation

Taiga-events in circus is stopped after a few seconds so I take a look at the components.

I am not able to start coffee with index.coffee

/usr/local/bin/coffee index.coffee

Please see error files attached.
![1](https://cloud.githubusercontent.com/assets/26148365/23522259/9b2ebfca-ff82-11e6-92c9-64f4904169eb.JPG)
![2](https://cloud.githubusercontent.com/assets/26148365/23522263/9eebba32-ff82-11e6-8956-e1f883a595c0.JPG)

Thank´s a lot!

**Comment by bameda** [comment]
This is like https://github.com/taigaio/taiga-events/issues/24 or https://github.com/taigaio/taiga-front/issues/1237

You are using an old version of node, please upgrade node to a version >= 6.0 (The current stable is 7.7.0 and the last LTS is 6.10.0 LTS).

**Comment by fabianfritz** [comment]
Thanks for your fast solution!

 

Best regards,

 

Fabian

Von: David Barragán Merino [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. März 2017 20:14
An: taigaio/taiga-events <taiga-events@noreply.github.com>
Cc: fabianfritz <fabian.fritz@forwardstofuture.de>; Author <author@noreply.github.com>
Betreff: Re: [taigaio/taiga-events] Taiga events: coffee returned error not typed array (#25)

 

This is like #24 <https://github.com/taigaio/taiga-events/issues/24>  or taigaio/taiga-front#1237 <https://github.com/taigaio/taiga-front/issues/1237> 

You are using an old version of node, please upgrade node to a version >= 6.0 (The current stable is 7.7.0 and the last LTS is 6.10.0 LTS).
