### ISSUE TITLE
Problem with editing editable-text fields asynchronously

### ISSUE THREAD

**Issue by Schwoebel** [taigaio/taiga-events#5]
I recently installed taiga-events and added these two lines to my local.py config.

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:*****@localhost:5672/taiga"}

What happens after restarting Taiga is when I try to edit any editable-text in any of my UserStories or related tasks  they are saved properly but the edit text field doesn't transition from being an edit-text field with a "save" icon back to a title field with an "edit"-pencil.  I get a big red error that says something went wrong and the changes aren't shown and I can't edit anything else on the page until I refresh the page.

I'm on the master-branch of the taiga-events repo.  And the only error message that I can find in any log is in gunicorn.stderr.log and the error is: 

ERROR:2015-10-02 11:20:02,426: Internal Server Error: /api/v1/userstories/293
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/mixins.py", line 170, in partial_update
    return self.update(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/transaction.py", line 382, in __exit__
    connection.set_autocommit(True)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 58, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/transaction_hooks/mixin.py", line 38, in run_and_clear_commit_hooks
    func()
  File "/home/taiga/taiga-back/taiga/events/signal_handlers.py", line 42, in <lambda>
    emit_event = lambda: events.emit_event_for_model(instance, sessionid=sesionid, type=type)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 78, in emit_event_for_model
    data=data)
  File "/home/taiga/taiga-back/taiga/events/events.py", line 44, in emit_event
    backend = backends.get_events_backend()
  File "/home/taiga/taiga-back/taiga/events/backends/base.py", line 59, in get_events_backend
    return cls(**options)
TypeError: object() takes no parameters

If I comment out those two events-lines and restart.  everything works fine.

**Comment by superalex** [comment]
Hello @Schwoebel 

What branch are you using for taiga-back?

**Comment by Schwoebel** [comment]
I am currently using the branch "stable"

**Comment by superalex** [comment]
I could only reproduce this issue if the setting EVENTS_PUSH_BACKEND_OPTIONS was correct but EVENTS_PUSH_BACKEND wasn't set. Could you paste here your local.py file for taiga-back to check if there is something wrong?.

Could you also paste here the content of taiga/events/backends/rabbitmq.py from your taiba-back copy of the repo?

Regards,

**Comment by Schwoebel** [comment]
of course I can.  
First local.py:
# Copyright (C) 2014 Andrey Antukh <niwi@niwi.be>
# Copyright (C) 2014 Jesús Espino <jespinog@gmail.com>
# Copyright (C) 2014 David Barragán <bameda@dbarragan.com>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from .development import *

DATABASES = {
    'default': {
        'ENGINE': 'transaction_hooks.backends.postgresql_psycopg2',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': 'changeme',
        'HOST': '',
        'PORT': '',
    }
}

INSTALLED_APPS += ["taiga_contrib_slack"]



EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:****@localhost:5672/taiga"}



#HOST="http://taiga.projects.kaleidos.net"
#
#MEDIA_ROOT = '/home/taiga/media'
#STATIC_ROOT = '/home/taiga/static'

# GMAIL SETTINGS EXAMPLE
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_USE_TLS = True
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'youremail@gmail.com'

# THROTTLING
#REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
#    "anon": "20/min",
#    "user": "200/min",
#    "import-mode": "20/sec",
#    "import-dump-mode": "1/minute"
#}

# GITHUB SETTINGS
#GITHUB_URL = "https://github.com/"
#GITHUB_API_URL = "https://api.github.com/"
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

# FEEDBACK MODULE (See config in taiga-front too)
#FEEDBACK_ENABLED = True
#FEEDBACK_EMAIL = "support@taiga.io"

# STATS MODULE
#STATS_ENABLED = False
#FRONT_SITEMAP_CACHE_TIMEOUT = 60*60  # In second

# SITEMAP
# If is True /front/sitemap.xml show a valid sitemap of taiga-front client
#FRONT_SITEMAP_ENABLED = False
#FRONT_SITEMAP_CACHE_TIMEOUT = 24*60*60  # In second

from .common import *

MEDIA_URL = "schwoebelsurl/media/"
STATIC_URL = "schwoebelsurl/static/"
ADMIN_MEDIA_PREFIX = "schwoebelsurl/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "schwoebelsurl"

SECRET_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxx"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "taiga@myurl.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = "localhost"
#EMAIL_HOST_USER = ""
#EMAIL_HOST_PASSWORD = ""
#EMAIL_PORT = 25

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"


from .celery import *

BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

and then rabbitmc.py:

# Copyright (C) 2014 Andrey Antukh <niwi@niwi.be>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import json
import logging

from amqp import Connection as AmqpConnection
from amqp.basic_message import Message as AmqpMessage
from urllib.parse import urlparse

from . import base

log = logging.getLogger("tagia.events")


def _make_rabbitmq_connection(url):
    parse_result = urlparse(url)

    # Parse host & user/password
    try:
        (authdata, host) = parse_result.netloc.split("@")
    except Exception as e:
        raise RuntimeError("Invalid url") from e

    try:
        (user, password) = authdata.split(":")
    except Exception:
        (user, password) = ("guest", "guest")

    vhost = parse_result.path
    return AmqpConnection(host=host, userid=user,
                          password=password, virtual_host=vhost[1:])


class EventsPushBackend(base.BaseEventsPushBackend):
    def __init__(self, url):
        self.url = url

    def emit_event(self, message:str, *, routing_key:str, channel:str="events"):
        connection = _make_rabbitmq_connection(self.url)

        try:
            rchannel = connection.channel()
            message = AmqpMessage(message)

            rchannel.exchange_declare(exchange=channel, type="topic", auto_delete=True)
            rchannel.basic_publish(message, routing_key=routing_key, exchange=channel)
  except Exception:
            log.error("Unhandled exception", exc_info=True)

        finally:
            connection.close()




I hope this helps.  I verified that EVENTS_PUSH_BACKEND was set.  And it is what it is above.

**Comment by superalex** [comment]
Your settings it's a bit strange, I think it could be related to having "from .common import *" in the middle of your file, that kind of import should be in the top but in the top you have "from .development import *" and that development.py yet includes common. Could you try removing that line from your local.py file and reload taiga-back?

**Comment by Schwoebel** [comment]
Ok. So I wasn't sure which line you meant to take out.  So I moved from .common import * to the top of the file.  Saved, restarted Taiga. And I got the same error message.  This time with a 500 error.  I 
followed the link that it got the 500 error from and I got to an API page with the following:

    GET /api/v1/tasks/307

    HTTP 401 UNAUTHORIZED
    WWW-Authenticate: Bearer realm="api"
    Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
    Vary: Accept
    Content-Type: application/json

    {
        "_error_message": "Authentication credentials were not provided.",
        "_error_type": "taiga.base.exceptions.NotAuthenticated"
    }

So that error is pretty clear except it doesn't tell me where I am suppose to provide the authentication info.

If it is in the EVENT_PUSH_BACKEND_OPTIONS variable, I provide the info there.

**Comment by superalex** [comment]
But in the top of the file you have a "from .development import *" that yet imports common, I suggested just removing that "from .common import *"

Are you having that auth error in the web app?, could you try to log out and log in again?

**Comment by Schwoebel** [comment]
I removed from.common import * and now I am not getting that error message
anymore.

It looks like that was the problem.

It may have been my unfamliarity with python.  The reason it was in the
middle of the file is because I was just copy and pasting from the
installation guide and not putting things in the right places.

**Comment by superalex** [comment]
Great!,

I'm very happy it's finally working! ;)
