### ISSUE TITLE
Can't Start Events

### ISSUE THREAD

**Issue by jppmateus** [taigaio/taiga-events#52]
Trying to update Taiga 5 to Taiga 6. Everything seems to work well, but I can't start taiga-events.

If I try to run the command manually, I receive this error:

~/taiga-events$ npm run start:production

> taigaio-events@6.0.1 start:production /home/taiga/taiga-events
> NODE_ENV=production node ./src/index.js

{"error":{},"level":"error","message":"uncaughtException: Unexpected token {\n/home/taiga/taiga-events/src/ws/client.js:74\n    } catch {\n            ^\n\nSyntaxError: Unexpected token {\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:617:28)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/home/taiga/taiga-events/src/ws/index.js:20:26)","stack":"/home/taiga/taiga-events/src/ws/client.js:74\n    } catch {\n            ^\n\nSyntaxError: Unexpected token {\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:617:28)\n    at Object.Module._extensions..js (module.js:664:10)\n    at Module.load (module.js:566:32)\n    at tryModuleLoad (module.js:506:12)\n    at Function.Module._load (module.js:498:3)\n    at Module.require (module.js:597:17)\n    at require (internal/module.js:11:18)\n    at Object.<anonymous> (/home/taiga/taiga-events/src/ws/index.js:20:26)","exception":true,"date":"Sun Feb 07 2021 05:05:10 GMT+0100 (CET)","process":{"pid":17199,"uid":1000,"gid":1000,"cwd":"/home/taiga/taiga-events","execPath":"/usr/bin/node","version":"v8.17.0","argv":["/usr/bin/node","/home/taiga/taiga-events/src/index.js"],"memoryUsage":{"rss":37457920,"heapTotal":12926976,"heapUsed":7682480,"external":76958}},"os":{"loadavg":[0.14404296875,0.1923828125,0.1787109375],"uptime":9538},"trace":[{"column":10,"file":"vm.js","function":"createScript","line":80,"method":null,"native":false},{"column":10,"file":"vm.js","function":"Object.runInThisContext","line":139,"method":"runInThisContext","native":false},{"column":28,"file":"module.js","function":"Module._compile","line":617,"method":"_compile","native":false},{"column":10,"file":"module.js","function":"Module._extensions..js","line":664,"method":".js","native":false},{"column":32,"file":"module.js","function":"Module.load","line":566,"method":"load","native":false},{"column":12,"file":"module.js","function":"tryModuleLoad","line":506,"method":null,"native":false},{"column":3,"file":"module.js","function":"Module._load","line":498,"method":"_load","native":false},{"column":17,"file":"module.js","function":"Module.require","line":597,"method":"require","native":false},{"column":18,"file":"internal/module.js","function":"require","line":11,"method":null,"native":false},{"column":26,"file":"/home/taiga/taiga-events/src/ws/index.js","function":null,"line":20,"method":null,"native":false}],"service":"taiga-events","timestamp":"2021-02-07 05:05:10"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taigaio-events@6.0.1 start:production: `NODE_ENV=production node ./src/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taigaio-events@6.0.1 start:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/taiga/.npm/_logs/2021-02-07T04_05_13_634Z-debug.log

**Comment by LecrisUT** [comment]
How does the `.env` file look like? Is the `SECRET` and `RABBITMQ_URL` setup correctly compared to the `taiga-back`'s `settings/config.py`? And what does ` /home/taiga/.npm/_logs/2021-02-07T04_05_13_634Z-debug.log` look like?

**Comment by jppmateus** [comment]
I will share with you:

.env

```
RABBITMQ_URL="amqp://taiga:SAzHf6pkQ852bK@localhost:5672/taiga"
SECRET="U#bS5bu5zY*VD4ism%uc*Wg4mp#gKgWgpYWJLw5K"
WEB_SOCKET_SERVER_PORT=8888
APP_PORT=3023
```

config.py:

```
SECRET_KEY = "U#bS5bu5zY*VD4ism%uc*Wg4mp#gKgWgpYWJLw5K"
CELERY_BROKER_URL = "amqp://taiga:SAzHf6pkQ852bK@localhost:5672/taiga"
```

log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start:production' ]
2 info using npm@6.13.4
3 info using node@v8.17.0
4 verbose run-script [ 'prestart:production',
4 verbose run-script   'start:production',
4 verbose run-script   'poststart:production' ]
5 info lifecycle taigaio-events@6.0.1~prestart:production: taigaio-events@6.0.1
6 info lifecycle taigaio-events@6.0.1~start:production: taigaio-events@6.0.1
7 verbose lifecycle taigaio-events@6.0.1~start:production: unsafe-perm in lifecycle true
8 verbose lifecycle taigaio-events@6.0.1~start:production: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/taiga/taiga-events/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle taigaio-events@6.0.1~start:production: CWD: /home/taiga/taiga-events
10 silly lifecycle taigaio-events@6.0.1~start:production: Args: [ '-c', 'NODE_ENV=production node ./src/index.js' ]
11 silly lifecycle taigaio-events@6.0.1~start:production: Returned: code: 1  signal: null
12 info lifecycle taigaio-events@6.0.1~start:production: Failed to exec start:production script
13 verbose stack Error: taigaio-events@6.0.1 start:production: `NODE_ENV=production node ./src/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid taigaio-events@6.0.1
15 verbose cwd /home/taiga/taiga-events
16 verbose Linux 4.15.0-74-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start:production"
18 verbose node v8.17.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error taigaio-events@6.0.1 start:production: `NODE_ENV=production node ./src/index.js`
22 error Exit status 1
23 error Failed at the taigaio-events@6.0.1 start:production script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by LecrisUT** [comment]
Hmm, the configuration looks fine. Try to `npm install` again, and make sure the ownership is set to `taiga` user and so on. Otherwise hopefully someone more proficient will come and help.

PS: don't forget to change the `SECRET` and other passwords afterwards

**Comment by jppmateus** [comment]
I already tried to run npm install again, and also move taiga-events for taiga-events-bck and do a new installation of the events.

@LecrisUT thanks anyway

**Comment by bameda** [comment]
Hi @jppmateus it seems that you are using a very old node version (`8.17.0`). Try to use someone equal or bigger than 12.x. There is a .nvmrc file in the repository if want to use [NVM](https://github.com/nvm-sh/nvm) (high recommended to work with different node versions).

Best regards

**Comment by jppmateus** [comment]
@bameda true. It's solved after upgrading Node. 

Thanks!

**Comment by bameda** [comment]
😀🎉
