### ISSUE TITLE
Unknown Response 200 on every page load.

### ISSUE THREAD

**Issue by Schwoebel** [taigaio/taiga-events#6]
After getting taiga-events up and running (confirmed with circusctl status taiga-events) I am getting and error message in my browser console (Firefox, Chrome) when I load any page.

    WebSocket connection to 'ws://taiga.iusinnovation.se/events' failed: Error during WebSocket        handshake: Unexpected response code: 200

When I go to the url http://taiga.iusinnovation.se/events/websocket I get a page that says nothing but "Not implemented".

my config file is right out of your installation docs:
{
    "url": "amqp://taiga:xxxxxxx@localhost:5672/taiga",
    "secret": "xxxxxx",
    "webSocketServer": {
        "port": 8888
    }
}

What I found in the code for Websocket is that IF the port is set in the config.json it is told to open a server, print that "Not implemented", close it, and stop.

I ran npm update coffee-script but it didn't update anything.

I am on the master branch of taiga-events.

Do you have any ideas why this is happening?

This may be the cause of my site not doing live-updates when moving kamban cards, editing tasks, etc....

**Comment by juanfran** [comment]
I don't know what might is happening....Could you try another port in webSocketServer?

**Comment by Schwoebel** [comment]
It doesn't seem to matter what port I try it in.  That error message is something that comes up from the WebSocket plugin itself.  And it comes up anytime the 'port' variable is set. 

I was doing some research and I noticed that the WebSocket plugin in taiga-events is a few versions behind the one in the Websicket GitHub repo.

Can you give me an idea of what *should* happen?  The documentation isn't exaclty clear.

**Comment by juanfran** [comment]
I've upgrade the websocket plugin in taiga-events but I think that it isn't the problem.

After runing circus and change the eventsUrl in taiga-front you should see something like this
![screenshot-14oct15-112336224](https://cloud.githubusercontent.com/assets/905195/10476980/ad44bbf6-7252-11e5-8c2c-4ee8ff55e579.png)

Is anything at the circus log?

**Comment by Schwoebel** [comment]
I *think* this has something to do with a reverse proxy my company has to run.

**Comment by superalex** [comment]
So should we close this one?

**Comment by Schwoebel** [comment]
Yes we can sir.

**Comment by bameda** [comment]
Good!!
